export const FETCHING_SECTION_DATA = "FETCHING_SECTION_DATA"
export const FETCHING_SECTION_DATA_SUCCESS = "FETCHING_SECTION_DATA_SUCCESS"
export const FETCHING_SECTION_DATA_FAIL = "FETCHING_SECTION_DATA_FAIL"