export const FETCHING_CONTENT_DATA = "FETCHING_CONTENT_DATA"
export const FETCHING_CONTENT_DATA_SUCCESS = "FETCHING_CONTENT_DATA_SUCCESS"
export const FETCHING_CONTENT_DATA_FAIL = "FETCHING_CONTENT_DATA_FAIL"